language: java
jdk: openjdk8
deploy:
  provider: releases
  api_key:
    secure: BUyj0vcUxK0jXB9BwM8jqTIysB6ZGj9Ld3aNxBvbl+wzGyLrtvtPQE1ukV8YXqfbPCA1OOJlKdN5Qsq6ieE+dHJEH4j61l6ogULVAbCJMkr3P3ejr2aWbwQEENAJFeA2Iky2u042KgNjqpqBLa/oR6Y9XiUszrVawzhHHC9dhUfWbvzYUnKxouwe34C+Gq9Sf0n2298bxlRapjvyK8WqkDX4bpob3bUYkHZK5JL6BCPDOwMjqsv/KCYaDWkFUdl/nhl7/BsKn2roYdvmkmilfNoZ09BbGPD2bW8UKD57W3B9ooqVxt2hU6pw7GrNH3G9t1OgrQKHoOXnX2HQB5qxKw5hPIbJPaznMcdDyA7SRgcsNS0BySTempQXZIr+kCVJZ/qPRh3cJdj0NnHpki95gQgqjajA5NErecwl1E1sButhzKFvC5tJYY2rXIn45nuR+KfW8IiNrhZC1acM9FBJ1DQbOIAWHEYMgHZ2PK+YlI7boccfhXxY5GmS1tELeFc1JcDdWpnBCTUfsb0M/g8vcmz7dkCo5D5zVrlN8juSynF2NHS2LuM8rw9yzI6MHxUxeUbRTtH5SM7DU2h3Eq+U31nlOPs2Ueh/Pw3OwLHOCyk3LgaD1JIjbfsWOahl5A6aBIywGwidt9hVN4PNV356VKr1ISTUp1kWTdKvnUcQA6E=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xlr-logreport-plugin
